// Generated by scripts/generate-ag-ui-schema.py from AG-UI 1.0 (db790c3).
// https://github.com/ag-ui-protocol/ag-ui/blob/db790c3/spec/1.0/schema.json
// AG-UI is MIT licensed; see ag-ui-LICENSE.txt. Do not edit by hand.
export const aguiSchema = {
  Event: {
    oneOf: [
      {
        ref: 'TextMessageStartEvent',
      },
      {
        ref: 'TextMessageContentEvent',
      },
      {
        ref: 'TextMessageEndEvent',
      },
      {
        ref: 'TextMessageChunkEvent',
      },
      {
        ref: 'ToolCallStartEvent',
      },
      {
        ref: 'ToolCallArgsEvent',
      },
      {
        ref: 'ToolCallEndEvent',
      },
      {
        ref: 'ToolCallChunkEvent',
      },
      {
        ref: 'ToolCallResultEvent',
      },
      {
        ref: 'StateSnapshotEvent',
      },
      {
        ref: 'StateDeltaEvent',
      },
      {
        ref: 'MessagesSnapshotEvent',
      },
      {
        ref: 'ActivitySnapshotEvent',
      },
      {
        ref: 'ActivityDeltaEvent',
      },
      {
        ref: 'RawEvent',
      },
      {
        ref: 'CustomEvent',
      },
      {
        ref: 'RunStartedEvent',
      },
      {
        ref: 'RunFinishedEvent',
      },
      {
        ref: 'RunErrorEvent',
      },
      {
        ref: 'StepStartedEvent',
      },
      {
        ref: 'StepFinishedEvent',
      },
      {
        ref: 'ReasoningStartEvent',
      },
      {
        ref: 'ReasoningMessageStartEvent',
      },
      {
        ref: 'ReasoningMessageContentEvent',
      },
      {
        ref: 'ReasoningMessageEndEvent',
      },
      {
        ref: 'ReasoningMessageChunkEvent',
      },
      {
        ref: 'ReasoningEndEvent',
      },
      {
        ref: 'ReasoningEncryptedValueEvent',
      },
      {
        ref: 'SubagentStartedEvent',
      },
      {
        ref: 'SubagentFinishedEvent',
      },
      {
        ref: 'SubagentErrorEvent',
      },
    ],
  },
  EventType: {
    type: 'string',
    enum: [
      'TEXT_MESSAGE_START',
      'TEXT_MESSAGE_CONTENT',
      'TEXT_MESSAGE_END',
      'TEXT_MESSAGE_CHUNK',
      'TOOL_CALL_START',
      'TOOL_CALL_ARGS',
      'TOOL_CALL_END',
      'TOOL_CALL_CHUNK',
      'TOOL_CALL_RESULT',
      'STATE_SNAPSHOT',
      'STATE_DELTA',
      'MESSAGES_SNAPSHOT',
      'ACTIVITY_SNAPSHOT',
      'ACTIVITY_DELTA',
      'RAW',
      'CUSTOM',
      'RUN_STARTED',
      'RUN_FINISHED',
      'RUN_ERROR',
      'STEP_STARTED',
      'STEP_FINISHED',
      'REASONING_START',
      'REASONING_MESSAGE_START',
      'REASONING_MESSAGE_CONTENT',
      'REASONING_MESSAGE_END',
      'REASONING_MESSAGE_CHUNK',
      'REASONING_END',
      'REASONING_ENCRYPTED_VALUE',
      'SUBAGENT_STARTED',
      'SUBAGENT_FINISHED',
      'SUBAGENT_ERROR',
    ],
  },
  BaseEvent: {
    type: 'object',
    properties: {
      type: {
        ref: 'EventType',
      },
      timestamp: {
        type: 'integer',
        minimum: -9007199254740991,
        maximum: 9007199254740991,
      },
      rawEvent: {
        not: {
          type: 'null',
        },
      },
      metadata: {
        ref: 'Metadata',
      },
    },
    required: ['type'],
  },
  Attributable: {
    type: 'object',
    properties: {
      subagentRunId: {
        ref: 'SubagentRunId',
      },
    },
  },
  SubagentRunId: {
    type: 'string',
  },
  Metadata: {
    type: 'object',
    additionalProperties: true,
  },
  State: {},
  TextMessageRole: {
    type: 'string',
    enum: ['developer', 'system', 'assistant', 'user'],
  },
  Role: {
    type: 'string',
    enum: [
      'developer',
      'system',
      'assistant',
      'user',
      'tool',
      'activity',
      'reasoning',
    ],
  },
  TextMessageStartEvent: {
    type: 'object',
    allOf: [
      {
        ref: 'BaseEvent',
      },
      {
        ref: 'Attributable',
      },
    ],
    properties: {
      type: {
        const: 'TEXT_MESSAGE_START',
      },
      messageId: {
        type: 'string',
      },
      role: {
        ref: 'TextMessageRole',
      },
      name: {
        type: 'string',
      },
    },
    required: ['type', 'messageId'],
    unevaluatedProperties: false,
  },
  TextMessageContentEvent: {
    type: 'object',
    allOf: [
      {
        ref: 'BaseEvent',
      },
      {
        ref: 'Attributable',
      },
    ],
    properties: {
      type: {
        const: 'TEXT_MESSAGE_CONTENT',
      },
      messageId: {
        type: 'string',
      },
      delta: {
        type: 'string',
      },
    },
    required: ['type', 'messageId', 'delta'],
    unevaluatedProperties: false,
  },
  TextMessageEndEvent: {
    type: 'object',
    allOf: [
      {
        ref: 'BaseEvent',
      },
      {
        ref: 'Attributable',
      },
    ],
    properties: {
      type: {
        const: 'TEXT_MESSAGE_END',
      },
      messageId: {
        type: 'string',
      },
    },
    required: ['type', 'messageId'],
    unevaluatedProperties: false,
  },
  TextMessageChunkEvent: {
    type: 'object',
    allOf: [
      {
        ref: 'BaseEvent',
      },
      {
        ref: 'Attributable',
      },
    ],
    properties: {
      type: {
        const: 'TEXT_MESSAGE_CHUNK',
      },
      messageId: {
        type: 'string',
      },
      role: {
        ref: 'TextMessageRole',
      },
      delta: {
        type: 'string',
      },
      name: {
        type: 'string',
      },
    },
    required: ['type'],
    unevaluatedProperties: false,
  },
  ToolCallStartEvent: {
    type: 'object',
    allOf: [
      {
        ref: 'BaseEvent',
      },
      {
        ref: 'Attributable',
      },
    ],
    properties: {
      type: {
        const: 'TOOL_CALL_START',
      },
      toolCallId: {
        type: 'string',
      },
      toolCallName: {
        type: 'string',
      },
      parentMessageId: {
        type: 'string',
      },
    },
    required: ['type', 'toolCallId', 'toolCallName'],
    unevaluatedProperties: false,
  },
  ToolCallArgsEvent: {
    type: 'object',
    allOf: [
      {
        ref: 'BaseEvent',
      },
      {
        ref: 'Attributable',
      },
    ],
    properties: {
      type: {
        const: 'TOOL_CALL_ARGS',
      },
      toolCallId: {
        type: 'string',
      },
      delta: {
        type: 'string',
      },
    },
    required: ['type', 'toolCallId', 'delta'],
    unevaluatedProperties: false,
  },
  ToolCallEndEvent: {
    type: 'object',
    allOf: [
      {
        ref: 'BaseEvent',
      },
      {
        ref: 'Attributable',
      },
    ],
    properties: {
      type: {
        const: 'TOOL_CALL_END',
      },
      toolCallId: {
        type: 'string',
      },
    },
    required: ['type', 'toolCallId'],
    unevaluatedProperties: false,
  },
  ToolCallChunkEvent: {
    type: 'object',
    allOf: [
      {
        ref: 'BaseEvent',
      },
      {
        ref: 'Attributable',
      },
    ],
    properties: {
      type: {
        const: 'TOOL_CALL_CHUNK',
      },
      toolCallId: {
        type: 'string',
      },
      toolCallName: {
        type: 'string',
      },
      parentMessageId: {
        type: 'string',
      },
      delta: {
        type: 'string',
      },
    },
    required: ['type'],
    unevaluatedProperties: false,
  },
  ToolCallResultEvent: {
    type: 'object',
    allOf: [
      {
        ref: 'BaseEvent',
      },
      {
        ref: 'Attributable',
      },
    ],
    properties: {
      type: {
        const: 'TOOL_CALL_RESULT',
      },
      messageId: {
        type: 'string',
      },
      toolCallId: {
        type: 'string',
      },
      content: {
        oneOf: [
          {
            type: 'string',
          },
          {
            type: 'array',
            items: {
              ref: 'ContentPart',
            },
          },
        ],
      },
      role: {
        const: 'tool',
      },
    },
    required: ['type', 'messageId', 'toolCallId', 'content'],
    unevaluatedProperties: false,
  },
  StateSnapshotEvent: {
    type: 'object',
    allOf: [
      {
        ref: 'BaseEvent',
      },
      {
        ref: 'Attributable',
      },
    ],
    properties: {
      type: {
        const: 'STATE_SNAPSHOT',
      },
      snapshot: {
        ref: 'State',
      },
    },
    required: ['type', 'snapshot'],
    unevaluatedProperties: false,
  },
  StateDeltaEvent: {
    type: 'object',
    allOf: [
      {
        ref: 'BaseEvent',
      },
      {
        ref: 'Attributable',
      },
    ],
    properties: {
      type: {
        const: 'STATE_DELTA',
      },
      delta: {
        ref: 'JsonPatch',
      },
    },
    required: ['type', 'delta'],
    unevaluatedProperties: false,
  },
  MessagesSnapshotEvent: {
    type: 'object',
    allOf: [
      {
        ref: 'BaseEvent',
      },
    ],
    properties: {
      type: {
        const: 'MESSAGES_SNAPSHOT',
      },
      messages: {
        type: 'array',
        items: {
          ref: 'Message',
        },
      },
    },
    required: ['type', 'messages'],
    unevaluatedProperties: false,
  },
  ActivitySnapshotEvent: {
    type: 'object',
    allOf: [
      {
        ref: 'BaseEvent',
      },
      {
        ref: 'Attributable',
      },
    ],
    properties: {
      type: {
        const: 'ACTIVITY_SNAPSHOT',
      },
      messageId: {
        type: 'string',
      },
      activityType: {
        type: 'string',
      },
      content: {
        type: 'object',
        additionalProperties: true,
      },
      replace: {
        type: 'boolean',
      },
    },
    required: ['type', 'messageId', 'activityType', 'content'],
    unevaluatedProperties: false,
  },
  ActivityDeltaEvent: {
    type: 'object',
    allOf: [
      {
        ref: 'BaseEvent',
      },
      {
        ref: 'Attributable',
      },
    ],
    properties: {
      type: {
        const: 'ACTIVITY_DELTA',
      },
      messageId: {
        type: 'string',
      },
      activityType: {
        type: 'string',
      },
      patch: {
        ref: 'JsonPatch',
      },
    },
    required: ['type', 'messageId', 'activityType', 'patch'],
    unevaluatedProperties: false,
  },
  RawEvent: {
    type: 'object',
    allOf: [
      {
        ref: 'BaseEvent',
      },
      {
        ref: 'Attributable',
      },
    ],
    properties: {
      type: {
        const: 'RAW',
      },
      event: {},
      source: {
        type: 'string',
      },
    },
    required: ['type', 'event'],
    unevaluatedProperties: false,
  },
  CustomEvent: {
    type: 'object',
    allOf: [
      {
        ref: 'BaseEvent',
      },
      {
        ref: 'Attributable',
      },
    ],
    properties: {
      type: {
        const: 'CUSTOM',
      },
      name: {
        type: 'string',
      },
      value: {},
    },
    required: ['type', 'name', 'value'],
    unevaluatedProperties: false,
  },
  RunStartedEvent: {
    type: 'object',
    allOf: [
      {
        ref: 'BaseEvent',
      },
    ],
    properties: {
      type: {
        const: 'RUN_STARTED',
      },
      threadId: {
        type: 'string',
      },
      runId: {
        type: 'string',
      },
      protocolVersion: {
        type: 'string',
      },
      parentRunId: {
        type: 'string',
      },
      input: {
        ref: 'RunAgentInput',
      },
    },
    required: ['type', 'threadId', 'runId'],
    unevaluatedProperties: false,
  },
  RunFinishedEvent: {
    type: 'object',
    allOf: [
      {
        ref: 'BaseEvent',
      },
    ],
    properties: {
      type: {
        const: 'RUN_FINISHED',
      },
      threadId: {
        type: 'string',
      },
      runId: {
        type: 'string',
      },
      result: {
        not: {
          type: 'null',
        },
      },
      outcome: {
        ref: 'RunFinishedOutcome',
      },
      usage: {
        type: 'array',
        items: {
          ref: 'TokenUsage',
        },
      },
    },
    required: ['type', 'threadId', 'runId'],
    unevaluatedProperties: false,
  },
  RunErrorEvent: {
    type: 'object',
    allOf: [
      {
        ref: 'BaseEvent',
      },
    ],
    properties: {
      type: {
        const: 'RUN_ERROR',
      },
      message: {
        type: 'string',
      },
      code: {
        type: 'string',
      },
      usage: {
        type: 'array',
        items: {
          ref: 'TokenUsage',
        },
      },
    },
    required: ['type', 'message'],
    unevaluatedProperties: false,
  },
  StepStartedEvent: {
    type: 'object',
    allOf: [
      {
        ref: 'BaseEvent',
      },
      {
        ref: 'Attributable',
      },
    ],
    properties: {
      type: {
        const: 'STEP_STARTED',
      },
      stepName: {
        type: 'string',
      },
    },
    required: ['type', 'stepName'],
    unevaluatedProperties: false,
  },
  StepFinishedEvent: {
    type: 'object',
    allOf: [
      {
        ref: 'BaseEvent',
      },
      {
        ref: 'Attributable',
      },
    ],
    properties: {
      type: {
        const: 'STEP_FINISHED',
      },
      stepName: {
        type: 'string',
      },
    },
    required: ['type', 'stepName'],
    unevaluatedProperties: false,
  },
  ReasoningStartEvent: {
    type: 'object',
    allOf: [
      {
        ref: 'BaseEvent',
      },
      {
        ref: 'Attributable',
      },
    ],
    properties: {
      type: {
        const: 'REASONING_START',
      },
      messageId: {
        type: 'string',
      },
    },
    required: ['type', 'messageId'],
    unevaluatedProperties: false,
  },
  ReasoningMessageStartEvent: {
    type: 'object',
    allOf: [
      {
        ref: 'BaseEvent',
      },
      {
        ref: 'Attributable',
      },
    ],
    properties: {
      type: {
        const: 'REASONING_MESSAGE_START',
      },
      messageId: {
        type: 'string',
      },
      role: {
        const: 'reasoning',
      },
    },
    required: ['type', 'messageId', 'role'],
    unevaluatedProperties: false,
  },
  ReasoningMessageContentEvent: {
    type: 'object',
    allOf: [
      {
        ref: 'BaseEvent',
      },
      {
        ref: 'Attributable',
      },
    ],
    properties: {
      type: {
        const: 'REASONING_MESSAGE_CONTENT',
      },
      messageId: {
        type: 'string',
      },
      delta: {
        type: 'string',
      },
    },
    required: ['type', 'messageId', 'delta'],
    unevaluatedProperties: false,
  },
  ReasoningMessageEndEvent: {
    type: 'object',
    allOf: [
      {
        ref: 'BaseEvent',
      },
      {
        ref: 'Attributable',
      },
    ],
    properties: {
      type: {
        const: 'REASONING_MESSAGE_END',
      },
      messageId: {
        type: 'string',
      },
    },
    required: ['type', 'messageId'],
    unevaluatedProperties: false,
  },
  ReasoningMessageChunkEvent: {
    type: 'object',
    allOf: [
      {
        ref: 'BaseEvent',
      },
      {
        ref: 'Attributable',
      },
    ],
    properties: {
      type: {
        const: 'REASONING_MESSAGE_CHUNK',
      },
      messageId: {
        type: 'string',
      },
      delta: {
        type: 'string',
      },
    },
    required: ['type'],
    unevaluatedProperties: false,
  },
  ReasoningEndEvent: {
    type: 'object',
    allOf: [
      {
        ref: 'BaseEvent',
      },
      {
        ref: 'Attributable',
      },
    ],
    properties: {
      type: {
        const: 'REASONING_END',
      },
      messageId: {
        type: 'string',
      },
    },
    required: ['type', 'messageId'],
    unevaluatedProperties: false,
  },
  ReasoningEncryptedValueEvent: {
    type: 'object',
    allOf: [
      {
        ref: 'BaseEvent',
      },
      {
        ref: 'Attributable',
      },
    ],
    properties: {
      type: {
        const: 'REASONING_ENCRYPTED_VALUE',
      },
      subtype: {
        ref: 'ReasoningEncryptedValueSubtype',
      },
      entityId: {
        type: 'string',
      },
      encryptedValue: {
        type: 'string',
      },
    },
    required: ['type', 'subtype', 'entityId', 'encryptedValue'],
    unevaluatedProperties: false,
  },
  ReasoningEncryptedValueSubtype: {
    type: 'string',
    enum: ['tool-call', 'message'],
  },
  SubagentStartedEvent: {
    type: 'object',
    allOf: [
      {
        ref: 'BaseEvent',
      },
    ],
    properties: {
      type: {
        const: 'SUBAGENT_STARTED',
      },
      subagentRunId: {
        ref: 'SubagentRunId',
      },
      name: {
        type: 'string',
      },
      description: {
        type: 'string',
      },
      parentSubagentRunId: {
        ref: 'SubagentRunId',
      },
      parentToolCallId: {
        type: 'string',
      },
      parentMessageId: {
        type: 'string',
      },
    },
    required: ['type', 'subagentRunId', 'name'],
    unevaluatedProperties: false,
  },
  SubagentFinishedEvent: {
    type: 'object',
    allOf: [
      {
        ref: 'BaseEvent',
      },
    ],
    properties: {
      type: {
        const: 'SUBAGENT_FINISHED',
      },
      subagentRunId: {
        ref: 'SubagentRunId',
      },
      result: {
        not: {
          type: 'null',
        },
      },
      outcome: {
        ref: 'SubagentFinishedOutcome',
      },
    },
    required: ['type', 'subagentRunId'],
    unevaluatedProperties: false,
  },
  SubagentErrorEvent: {
    type: 'object',
    allOf: [
      {
        ref: 'BaseEvent',
      },
    ],
    properties: {
      type: {
        const: 'SUBAGENT_ERROR',
      },
      subagentRunId: {
        ref: 'SubagentRunId',
      },
      message: {
        type: 'string',
      },
      code: {
        type: 'string',
      },
    },
    required: ['type', 'subagentRunId', 'message'],
    unevaluatedProperties: false,
  },
  RunFinishedOutcome: {
    oneOf: [
      {
        ref: 'RunFinishedSuccessOutcome',
      },
      {
        ref: 'RunFinishedInterruptOutcome',
      },
      {
        ref: 'RunFinishedCancelledOutcome',
      },
    ],
  },
  RunFinishedSuccessOutcome: {
    type: 'object',
    properties: {
      type: {
        const: 'success',
      },
      pendingToolCallIds: {
        type: 'array',
        items: {
          type: 'string',
        },
      },
    },
    required: ['type'],
    unevaluatedProperties: false,
  },
  RunFinishedInterruptOutcome: {
    type: 'object',
    properties: {
      type: {
        const: 'interrupt',
      },
      interrupts: {
        type: 'array',
        minItems: 1,
        items: {
          ref: 'Interrupt',
        },
      },
    },
    required: ['type', 'interrupts'],
    unevaluatedProperties: false,
  },
  RunFinishedCancelledOutcome: {
    type: 'object',
    properties: {
      type: {
        const: 'cancelled',
      },
    },
    required: ['type'],
    unevaluatedProperties: false,
  },
  SubagentFinishedOutcome: {
    oneOf: [
      {
        ref: 'SubagentFinishedSuccessOutcome',
      },
      {
        ref: 'SubagentFinishedSuspendedOutcome',
      },
    ],
  },
  SubagentFinishedSuccessOutcome: {
    type: 'object',
    properties: {
      type: {
        const: 'success',
      },
    },
    required: ['type'],
    unevaluatedProperties: false,
  },
  SubagentFinishedSuspendedOutcome: {
    type: 'object',
    properties: {
      type: {
        const: 'suspended',
      },
      interruptIds: {
        type: 'array',
        items: {
          type: 'string',
        },
      },
    },
    required: ['type'],
    unevaluatedProperties: false,
  },
  Interrupt: {
    type: 'object',
    allOf: [
      {
        ref: 'Attributable',
      },
    ],
    properties: {
      id: {
        type: 'string',
      },
      reason: {
        type: 'string',
      },
      message: {
        type: 'string',
      },
      toolCallId: {
        type: 'string',
      },
      responseSchema: {
        type: 'object',
        additionalProperties: true,
      },
      expiresAt: {
        type: 'string',
      },
      metadata: {
        ref: 'Metadata',
      },
    },
    required: ['id', 'reason'],
    unevaluatedProperties: false,
  },
  ResumeEntry: {
    type: 'object',
    properties: {
      interruptId: {
        type: 'string',
      },
      status: {
        type: 'string',
        enum: ['resolved', 'cancelled'],
      },
      payload: {
        not: {
          type: 'null',
        },
      },
      metadata: {
        ref: 'Metadata',
      },
    },
    required: ['interruptId', 'status'],
    unevaluatedProperties: false,
  },
  TokenUsage: {
    type: 'object',
    properties: {
      provider: {
        type: 'string',
      },
      model: {
        type: 'string',
      },
      inputTokens: {
        type: 'integer',
        minimum: 0,
        maximum: 9007199254740991,
      },
      outputTokens: {
        type: 'integer',
        minimum: 0,
        maximum: 9007199254740991,
      },
      totalTokens: {
        type: 'integer',
        minimum: 0,
        maximum: 9007199254740991,
      },
      reasoningTokens: {
        type: 'integer',
        minimum: 0,
        maximum: 9007199254740991,
      },
      cachedInputTokens: {
        type: 'integer',
        minimum: 0,
        maximum: 9007199254740991,
      },
      cacheWriteInputTokens: {
        type: 'integer',
        minimum: 0,
        maximum: 9007199254740991,
      },
    },
    unevaluatedProperties: false,
  },
  Message: {
    oneOf: [
      {
        ref: 'DeveloperMessage',
      },
      {
        ref: 'SystemMessage',
      },
      {
        ref: 'AssistantMessage',
      },
      {
        ref: 'UserMessage',
      },
      {
        ref: 'ToolMessage',
      },
      {
        ref: 'ActivityMessage',
      },
      {
        ref: 'ReasoningMessage',
      },
    ],
  },
  BaseMessage: {
    type: 'object',
    allOf: [
      {
        ref: 'Attributable',
      },
    ],
    properties: {
      id: {
        type: 'string',
      },
      role: {
        type: 'string',
      },
      name: {
        type: 'string',
      },
      encryptedValue: {
        type: 'string',
      },
      metadata: {
        ref: 'Metadata',
      },
    },
    required: ['id', 'role'],
  },
  DeveloperMessage: {
    type: 'object',
    allOf: [
      {
        ref: 'BaseMessage',
      },
    ],
    properties: {
      role: {
        const: 'developer',
      },
      content: {
        type: 'string',
      },
    },
    required: ['id', 'role', 'content'],
    unevaluatedProperties: false,
  },
  SystemMessage: {
    type: 'object',
    allOf: [
      {
        ref: 'BaseMessage',
      },
    ],
    properties: {
      role: {
        const: 'system',
      },
      content: {
        type: 'string',
      },
    },
    required: ['id', 'role', 'content'],
    unevaluatedProperties: false,
  },
  AssistantMessage: {
    type: 'object',
    allOf: [
      {
        ref: 'BaseMessage',
      },
    ],
    properties: {
      role: {
        const: 'assistant',
      },
      content: {
        type: 'string',
      },
      toolCalls: {
        type: 'array',
        items: {
          ref: 'ToolCall',
        },
      },
    },
    required: ['id', 'role'],
    unevaluatedProperties: false,
  },
  UserMessage: {
    type: 'object',
    allOf: [
      {
        ref: 'BaseMessage',
      },
    ],
    properties: {
      role: {
        const: 'user',
      },
      content: {
        oneOf: [
          {
            type: 'string',
          },
          {
            type: 'array',
            items: {
              ref: 'ContentPart',
            },
          },
        ],
      },
    },
    required: ['id', 'role', 'content'],
    unevaluatedProperties: false,
  },
  ToolMessage: {
    type: 'object',
    allOf: [
      {
        ref: 'Attributable',
      },
    ],
    properties: {
      id: {
        type: 'string',
      },
      role: {
        const: 'tool',
      },
      content: {
        oneOf: [
          {
            type: 'string',
          },
          {
            type: 'array',
            items: {
              ref: 'ContentPart',
            },
          },
        ],
      },
      toolCallId: {
        type: 'string',
      },
      error: {
        type: 'string',
      },
      encryptedValue: {
        type: 'string',
      },
      metadata: {
        ref: 'Metadata',
      },
    },
    required: ['id', 'role', 'content', 'toolCallId'],
    unevaluatedProperties: false,
  },
  ActivityMessage: {
    type: 'object',
    allOf: [
      {
        ref: 'Attributable',
      },
    ],
    properties: {
      id: {
        type: 'string',
      },
      role: {
        const: 'activity',
      },
      activityType: {
        type: 'string',
      },
      content: {
        type: 'object',
        additionalProperties: true,
      },
      metadata: {
        ref: 'Metadata',
      },
    },
    required: ['id', 'role', 'activityType', 'content'],
    unevaluatedProperties: false,
  },
  ReasoningMessage: {
    type: 'object',
    allOf: [
      {
        ref: 'Attributable',
      },
    ],
    properties: {
      id: {
        type: 'string',
      },
      role: {
        const: 'reasoning',
      },
      content: {
        type: 'string',
      },
      encryptedValue: {
        type: 'string',
      },
      metadata: {
        ref: 'Metadata',
      },
    },
    required: ['id', 'role', 'content'],
    unevaluatedProperties: false,
  },
  ToolCall: {
    type: 'object',
    properties: {
      id: {
        type: 'string',
      },
      type: {
        const: 'function',
      },
      function: {
        ref: 'FunctionCall',
      },
      encryptedValue: {
        type: 'string',
      },
      metadata: {
        ref: 'Metadata',
      },
    },
    required: ['id', 'type', 'function'],
    unevaluatedProperties: false,
  },
  FunctionCall: {
    type: 'object',
    properties: {
      name: {
        type: 'string',
      },
      arguments: {
        type: 'string',
      },
    },
    required: ['name', 'arguments'],
    unevaluatedProperties: false,
  },
  ContentPart: {
    oneOf: [
      {
        ref: 'TextPart',
      },
      {
        ref: 'ImagePart',
      },
      {
        ref: 'AudioPart',
      },
      {
        ref: 'VideoPart',
      },
      {
        ref: 'DocumentPart',
      },
    ],
  },
  TextPart: {
    type: 'object',
    properties: {
      type: {
        const: 'text',
      },
      id: {
        type: 'string',
      },
      text: {
        type: 'string',
      },
      metadata: {
        not: {
          type: 'null',
        },
      },
    },
    required: ['type', 'text'],
    unevaluatedProperties: false,
  },
  ImagePart: {
    type: 'object',
    properties: {
      type: {
        const: 'image',
      },
      id: {
        type: 'string',
      },
      source: {
        ref: 'PartSource',
      },
      metadata: {
        not: {
          type: 'null',
        },
      },
    },
    required: ['type', 'source'],
    unevaluatedProperties: false,
  },
  AudioPart: {
    type: 'object',
    properties: {
      type: {
        const: 'audio',
      },
      id: {
        type: 'string',
      },
      source: {
        ref: 'PartSource',
      },
      metadata: {
        not: {
          type: 'null',
        },
      },
    },
    required: ['type', 'source'],
    unevaluatedProperties: false,
  },
  VideoPart: {
    type: 'object',
    properties: {
      type: {
        const: 'video',
      },
      id: {
        type: 'string',
      },
      source: {
        ref: 'PartSource',
      },
      metadata: {
        not: {
          type: 'null',
        },
      },
    },
    required: ['type', 'source'],
    unevaluatedProperties: false,
  },
  DocumentPart: {
    type: 'object',
    properties: {
      type: {
        const: 'document',
      },
      id: {
        type: 'string',
      },
      source: {
        ref: 'PartSource',
      },
      metadata: {
        not: {
          type: 'null',
        },
      },
    },
    required: ['type', 'source'],
    unevaluatedProperties: false,
  },
  PartSource: {
    oneOf: [
      {
        ref: 'DataSource',
      },
      {
        ref: 'UrlSource',
      },
      {
        ref: 'FileSource',
      },
    ],
  },
  DataSource: {
    type: 'object',
    properties: {
      type: {
        const: 'data',
      },
      value: {
        type: 'string',
      },
      mimeType: {
        type: 'string',
      },
    },
    required: ['type', 'value', 'mimeType'],
    unevaluatedProperties: false,
  },
  UrlSource: {
    type: 'object',
    properties: {
      type: {
        const: 'url',
      },
      value: {
        type: 'string',
      },
      mimeType: {
        type: 'string',
      },
    },
    required: ['type', 'value'],
    unevaluatedProperties: false,
  },
  FileSource: {
    type: 'object',
    properties: {
      type: {
        const: 'file',
      },
      value: {
        type: 'string',
      },
      provider: {
        type: 'string',
      },
      mimeType: {
        type: 'string',
      },
    },
    required: ['type', 'value'],
    unevaluatedProperties: false,
  },
  Context: {
    type: 'object',
    properties: {
      description: {
        type: 'string',
      },
      value: {
        type: 'string',
      },
    },
    required: ['description', 'value'],
    unevaluatedProperties: false,
  },
  Tool: {
    type: 'object',
    properties: {
      name: {
        type: 'string',
      },
      description: {
        type: 'string',
      },
      parameters: {
        not: {
          type: 'null',
        },
      },
      metadata: {
        ref: 'Metadata',
      },
    },
    required: ['name', 'description'],
    unevaluatedProperties: false,
  },
  RunAgentInput: {
    type: 'object',
    properties: {
      threadId: {
        type: 'string',
      },
      runId: {
        type: 'string',
      },
      protocolVersion: {
        type: 'string',
      },
      parentRunId: {
        type: 'string',
      },
      state: {
        not: {
          type: 'null',
        },
        ref: 'State',
      },
      messages: {
        type: 'array',
        items: {
          ref: 'Message',
        },
      },
      tools: {
        type: 'array',
        items: {
          ref: 'Tool',
        },
      },
      context: {
        type: 'array',
        items: {
          ref: 'Context',
        },
      },
      forwardedProps: {
        not: {
          type: 'null',
        },
      },
      resume: {
        type: 'array',
        items: {
          ref: 'ResumeEntry',
        },
      },
    },
    required: ['threadId', 'runId', 'messages'],
    unevaluatedProperties: false,
  },
  SubagentInfo: {
    type: 'object',
    properties: {
      name: {
        type: 'string',
      },
      description: {
        type: 'string',
      },
    },
    required: ['name'],
    unevaluatedProperties: false,
  },
  IdentityCapabilities: {
    type: 'object',
    properties: {
      name: {
        type: 'string',
      },
      type: {
        type: 'string',
      },
      description: {
        type: 'string',
      },
      version: {
        type: 'string',
      },
      provider: {
        type: 'string',
      },
      documentationUrl: {
        type: 'string',
      },
      metadata: {
        ref: 'Metadata',
      },
    },
    unevaluatedProperties: false,
  },
  TransportCapabilities: {
    type: 'object',
    properties: {
      streaming: {
        type: 'boolean',
      },
      websocket: {
        type: 'boolean',
      },
      httpBinary: {
        type: 'boolean',
      },
      pushNotifications: {
        type: 'boolean',
      },
      resumable: {
        type: 'boolean',
      },
    },
    unevaluatedProperties: false,
  },
  ToolsCapabilities: {
    type: 'object',
    properties: {
      supported: {
        type: 'boolean',
      },
      items: {
        type: 'array',
        items: {
          ref: 'Tool',
        },
      },
      parallelCalls: {
        type: 'boolean',
      },
      clientProvided: {
        type: 'boolean',
      },
    },
    unevaluatedProperties: false,
  },
  OutputCapabilities: {
    type: 'object',
    properties: {
      structuredOutput: {
        type: 'boolean',
      },
      supportedMimeTypes: {
        type: 'array',
        items: {
          type: 'string',
        },
      },
    },
    unevaluatedProperties: false,
  },
  StateCapabilities: {
    type: 'object',
    properties: {
      snapshots: {
        type: 'boolean',
      },
      deltas: {
        type: 'boolean',
      },
      memory: {
        type: 'boolean',
      },
      persistentState: {
        type: 'boolean',
      },
    },
    unevaluatedProperties: false,
  },
  MultiAgentCapabilities: {
    type: 'object',
    properties: {
      supported: {
        type: 'boolean',
      },
      delegation: {
        type: 'boolean',
      },
      handoffs: {
        type: 'boolean',
      },
      subagents: {
        type: 'array',
        items: {
          ref: 'SubagentInfo',
        },
      },
    },
    unevaluatedProperties: false,
  },
  ReasoningCapabilities: {
    type: 'object',
    properties: {
      supported: {
        type: 'boolean',
      },
      streaming: {
        type: 'boolean',
      },
      encrypted: {
        type: 'boolean',
      },
    },
    unevaluatedProperties: false,
  },
  MultimodalInputCapabilities: {
    type: 'object',
    properties: {
      image: {
        type: 'boolean',
      },
      audio: {
        type: 'boolean',
      },
      video: {
        type: 'boolean',
      },
      pdf: {
        type: 'boolean',
      },
      file: {
        type: 'boolean',
      },
    },
    unevaluatedProperties: false,
  },
  MultimodalOutputCapabilities: {
    type: 'object',
    properties: {
      image: {
        type: 'boolean',
      },
      audio: {
        type: 'boolean',
      },
    },
    unevaluatedProperties: false,
  },
  MultimodalCapabilities: {
    type: 'object',
    properties: {
      input: {
        ref: 'MultimodalInputCapabilities',
      },
      output: {
        ref: 'MultimodalOutputCapabilities',
      },
    },
    unevaluatedProperties: false,
  },
  ExecutionCapabilities: {
    type: 'object',
    properties: {
      codeExecution: {
        type: 'boolean',
      },
      sandboxed: {
        type: 'boolean',
      },
      maxIterations: {
        type: 'integer',
        minimum: 0,
        maximum: 9007199254740991,
      },
      maxExecutionTime: {
        type: 'integer',
        minimum: 0,
        maximum: 9007199254740991,
      },
    },
    unevaluatedProperties: false,
  },
  HumanInTheLoopCapabilities: {
    type: 'object',
    properties: {
      supported: {
        type: 'boolean',
      },
      approvals: {
        type: 'boolean',
      },
      interventions: {
        type: 'boolean',
      },
      feedback: {
        type: 'boolean',
      },
      interrupts: {
        type: 'boolean',
      },
      approveWithEdits: {
        type: 'boolean',
      },
    },
    unevaluatedProperties: false,
  },
  AgentCapabilities: {
    type: 'object',
    properties: {
      identity: {
        ref: 'IdentityCapabilities',
      },
      transport: {
        ref: 'TransportCapabilities',
      },
      tools: {
        ref: 'ToolsCapabilities',
      },
      output: {
        ref: 'OutputCapabilities',
      },
      state: {
        ref: 'StateCapabilities',
      },
      multiAgent: {
        ref: 'MultiAgentCapabilities',
      },
      reasoning: {
        ref: 'ReasoningCapabilities',
      },
      multimodal: {
        ref: 'MultimodalCapabilities',
      },
      execution: {
        ref: 'ExecutionCapabilities',
      },
      humanInTheLoop: {
        ref: 'HumanInTheLoopCapabilities',
      },
      custom: {
        type: 'object',
        additionalProperties: true,
      },
    },
    unevaluatedProperties: false,
  },
  JsonPatch: {
    type: 'array',
    items: {
      ref: 'JsonPatchOperation',
    },
  },
  JsonPatchOperation: {
    oneOf: [
      {
        ref: 'AddOperation',
      },
      {
        ref: 'RemoveOperation',
      },
      {
        ref: 'ReplaceOperation',
      },
      {
        ref: 'MoveOperation',
      },
      {
        ref: 'CopyOperation',
      },
      {
        ref: 'TestOperation',
      },
    ],
  },
  AddOperation: {
    type: 'object',
    properties: {
      op: {
        const: 'add',
      },
      path: {
        ref: 'JsonPointer',
      },
      value: {},
    },
    required: ['op', 'path', 'value'],
  },
  RemoveOperation: {
    type: 'object',
    properties: {
      op: {
        const: 'remove',
      },
      path: {
        ref: 'JsonPointer',
      },
    },
    required: ['op', 'path'],
  },
  ReplaceOperation: {
    type: 'object',
    properties: {
      op: {
        const: 'replace',
      },
      path: {
        ref: 'JsonPointer',
      },
      value: {},
    },
    required: ['op', 'path', 'value'],
  },
  MoveOperation: {
    type: 'object',
    properties: {
      op: {
        const: 'move',
      },
      from: {
        ref: 'JsonPointer',
      },
      path: {
        ref: 'JsonPointer',
      },
    },
    required: ['op', 'from', 'path'],
  },
  CopyOperation: {
    type: 'object',
    properties: {
      op: {
        const: 'copy',
      },
      from: {
        ref: 'JsonPointer',
      },
      path: {
        ref: 'JsonPointer',
      },
    },
    required: ['op', 'from', 'path'],
  },
  TestOperation: {
    type: 'object',
    properties: {
      op: {
        const: 'test',
      },
      path: {
        ref: 'JsonPointer',
      },
      value: {},
    },
    required: ['op', 'path', 'value'],
  },
  JsonPointer: {
    type: 'string',
    pattern: '^(/([^/~]|~[01])*)*$',
  },
}
