"""Generate dependency-free descriptors from the official AG-UI 1.0 schema.

Usage: python3 packages/ai/scripts/generate-ag-ui-schema.py /path/to/spec/1.0/schema.json
Source: https://github.com/ag-ui-protocol/ag-ui/tree/db790c3/spec/1.0
Only validation keywords used by this schema are supported; fail on additions.
"""
import json
import sys
from pathlib import Path

source = json.loads(Path(sys.argv[1]).read_text())
ignored = {'$anchor', 'description', 'default', 'contentEncoding'}
supported = {'$ref', 'type', 'properties', 'required', 'allOf', 'oneOf', 'items', 'not', 'minimum', 'maximum', 'enum', 'const', 'additionalProperties', 'unevaluatedProperties', 'minItems', 'pattern'}

def compact(schema):
    result = {}
    for key, value in schema.items():
        if key in ignored:
            continue
        if key not in supported:
            raise ValueError(f'Unsupported keyword: {key}')
        if key == '$ref':
            result['ref'] = value.split('/')[-1]
        elif key == 'properties':
            result[key] = {name: compact(child) for name, child in value.items()}
        elif key in ('allOf', 'oneOf'):
            result[key] = [compact(child) for child in value]
        elif key in ('items', 'not'):
            result[key] = compact(value)
        else:
            result[key] = value
    return result

descriptors = {name: compact(schema) for name, schema in source['$defs'].items()}
Path('packages/ai/src/utilities/ag-ui-schema.ts').write_text(
    '// Generated by scripts/generate-ag-ui-schema.py from AG-UI 1.0 (db790c3).\n'
    '// https://github.com/ag-ui-protocol/ag-ui/blob/db790c3/spec/1.0/schema.json\n'
    '// AG-UI is MIT licensed; see ag-ui-LICENSE.txt. Do not edit by hand.\n'
    'export const aguiSchema = ' + json.dumps(descriptors, indent=2) + '\n')
